var_1 DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0f8f8f8h, 0f2f2f2h, 0fdfdfdh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0fefefeh, 0f5f5f5h, 0e8e8e8h, 0d5d5d5h, 0bdbdbdh, 0a2a2a2h, 07e7e7eh, 08d8d8dh, 0eeeeeeh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0c4c4c4h, 06d6d6dh, 0525252h, 0414141h, 02c2c2ch, 0151515h, 0010101h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0a1a1a1h, 0202020h, 0070707h, 0070707h, 0000000h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0eeeeeeh, 0d8d8d8h, 0d3d3d3h, 0d3d3d3h, 0111111h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0151515h, 0000000h, 0000000h, 03a3a3ah, 0e2e2e2h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0f9f9f9h, 0111111h, 0000000h, 0000000h, 0373737h, 0dcdcdch, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0c8c8c8h, 07c7c7ch, 06d6d6dh, 0575757h, 0050505h, 0000000h, 0000000h, 0121212h, 0525252h, 06c6c6ch, 08f8f8fh, 0edededh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0a3a3a3h, 0232323h, 0090909h, 0050505h, 0000000h, 0000000h, 0000000h, 0010101h, 0050505h, 0090909h, 0424242h, 0e1e1e1h, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0e7e7e7h, 0c6c6c6h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0c0c0c0h, 0cfcfcfh, 0f7f7f7h, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0fefefeh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fefefeh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0fdfdfdh, 0fafafah, 0f8f8f8h, 0f8f8f8h, 0f8f8f8h, 0fafafah, 0fbfbfbh

