var_7 DD 0f7f7f7h, 0fefefeh, 0fdfdfdh, 0ebebebh, 0ffffffh, 0f9f9f9h, 0fcfcfch, 0ffffffh, 0ffffffh, 0fdfdfdh, 0f5f5f5h, 0fafafah, 0ffffffh, 0f6f6f6h, 0ffffffh, 0f8f8f8h, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0fdfdfdh, 0ffffffh, 0ffffffh, 0dededeh, 0d1d1d1h, 0cccccch, 0c8c8c8h, 0b8b8b8h, 0c8c8c8h, 0d8d8d8h, 0c8c8c8h, 0cdcdcdh, 0e4e4e4h, 0fafafah, 0fdfdfdh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0f1f1f1h, 0fbfbfbh, 0f7f7f7h, 05f5f5fh, 02f2f2fh, 0282828h, 02b2b2bh, 0444444h, 0222222h, 03c3c3ch, 0303030h, 0242424h, 0979797h, 0f6f6f6h, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0f7f7f7h, 0ffffffh, 0f0f0f0h, 0404040h, 0030303h, 0000000h, 0080808h, 0010101h, 0000000h, 0070707h, 0000000h, 0080808h, 0999999h, 0f3f3f3h, 0efefefh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0fbfbfbh, 0ffffffh, 0fbfbfbh, 0b2b2b2h, 09c9c9ch, 0989898h, 0989898h, 0969696h, 0a4a4a4h, 0303030h, 0000000h, 0464646h, 0cccccch, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fafafah, 0fafafah, 0f4f4f4h, 0f5f5f5h, 0fdfdfdh, 0ffffffh, 0fafafah, 0f6f6f6h, 0ffffffh, 0acacach, 0171717h, 0282828h, 0aaaaaah, 0f5f5f5h, 0ffffffh, 0f9f9f9h, 0ffffffh, 0ffffffh
      DD 0fbfbfbh, 0ffffffh, 0fbfbfbh, 0f7f7f7h, 0fefefeh, 0fdfdfdh, 0f4f4f4h, 0f9f9f9h, 0f3f3f3h, 0323232h, 0000000h, 0767676h, 0e7e7e7h, 0fdfdfdh, 0ffffffh, 0f8f8f8h, 0ffffffh, 0ffffffh
      DD 0f9f9f9h, 0ffffffh, 0fbfbfbh, 0ffffffh, 0fefefeh, 0ffffffh, 0f5f5f5h, 0ffffffh, 0a3a3a3h, 0080808h, 02c2c2ch, 0b5b5b5h, 0ffffffh, 0f9f9f9h, 0f9f9f9h, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fdfdfdh, 0ffffffh, 0fafafah, 0f9f9f9h, 0fefefeh, 0fdfdfdh, 0fcfcfch, 0f7f7f7h, 02a2a2ah, 0000000h, 0525252h, 0efefefh, 0ffffffh, 0ffffffh, 0f6f6f6h, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fbfbfbh, 0fafafah, 0ffffffh, 0fefefeh, 0ffffffh, 0fcfcfch, 0ffffffh, 0a5a5a5h, 00e0e0eh, 0080808h, 0a0a0a0h, 0fafafah, 0f9f9f9h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fefefeh, 0f8f8f8h, 0ffffffh, 0fbfbfbh, 0ffffffh, 0f5f5f5h, 0f6f6f6h, 03b3b3bh, 0020202h, 0232323h, 0ececech, 0ffffffh, 0f9f9f9h, 0fefefeh, 0ffffffh, 0fefefeh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0f7f7f7h, 0ffffffh, 0f4f4f4h, 0fefefeh, 0fafafah, 0d1d1d1h, 0080808h, 0090909h, 0575757h, 0ffffffh, 0fefefeh, 0ffffffh, 0f7f7f7h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fdfdfdh, 0f8f8f8h, 0ffffffh, 0f5f5f5h, 0fcfcfch, 0ffffffh, 0989898h, 0070707h, 0030303h, 09d9d9dh, 0ffffffh, 0f5f5f5h, 0ffffffh, 0f7f7f7h, 0fdfdfdh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fefefeh, 0fbfbfbh, 0ffffffh, 0fbfbfbh, 0f9f9f9h, 0ffffffh, 0575757h, 0050505h, 0000000h, 0d7d7d7h, 0ffffffh, 0f4f4f4h, 0fafafah, 0fdfdfdh, 0ffffffh, 0fefefeh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0f9f9f9h, 0ffffffh, 0fdfdfdh, 0fafafah, 0f7f7f7h, 03c3c3ch, 0070707h, 00a0a0ah, 0f0f0f0h, 0ffffffh, 0fdfdfdh, 0f8f8f8h, 0ffffffh, 0ffffffh, 0fefefeh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0f2f2f2h, 0fcfcfch, 0fdfdfdh, 0ffffffh, 0fafafah, 04c4c4ch, 01a1a1ah, 02f2f2fh, 0f0f0f0h, 0fdfdfdh, 0ffffffh, 0fdfdfdh, 0fdfdfdh, 0fefefeh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0f8f8f8h, 0fdfdfdh, 0fcfcfch, 0f7f7f7h, 0f7f7f7h, 0f9f9f9h, 0f6f6f6h, 0eeeeeeh, 0f9f9f9h, 0fbfbfbh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fefefeh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0fbfbfbh, 0ffffffh, 0ffffffh, 0fbfbfbh, 0fafafah, 0fdfdfdh, 0fafafah, 0f2f2f2h, 0fafafah, 0fcfcfch, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0fdfdfdh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh

