var_2 DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0fdfdfdh, 0d0d0d0h, 0a6a6a6h, 0999999h, 0a8a8a8h, 0d3d3d3h, 0fefefeh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0b1b1b1h, 0232323h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 02d2d2dh, 0c7c7c7h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0bbbbbbh, 0020202h, 0000000h, 0010101h, 0414141h, 0626262h, 0303030h, 0000000h, 0000000h, 00b0b0bh, 0d7d7d7h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0444444h, 0000000h, 0000000h, 07d7d7dh, 0ffffffh, 0ffffffh, 0fefefeh, 04a4a4ah, 0000000h, 0000000h, 0727272h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0aaaaaah, 08e8e8eh, 07a7a7ah, 0e0e0e0h, 0ffffffh, 0ffffffh, 0ffffffh, 0777777h, 0000000h, 0000000h, 0676767h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ececech, 01d1d1dh, 0000000h, 0000000h, 0abababh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0dbdbdbh, 02a2a2ah, 0000000h, 0000000h, 0464646h, 0fefefeh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0a7a7a7h, 00f0f0fh, 0000000h, 0000000h, 03e3e3eh, 0f1f1f1h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0f7f7f7h, 0656565h, 0000000h, 0000000h, 0010101h, 0717171h, 0fafafah, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0e8e8e8h, 0353535h, 0000000h, 0000000h, 0171717h, 0b7b7b7h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ebebebh, 0272727h, 0000000h, 0000000h, 02c2c2ch, 0e5e5e5h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0565656h, 0000000h, 0000000h, 0000000h, 0030303h, 0060606h, 0060606h, 0060606h, 0060606h, 0060606h, 0636363h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0e1e1e1h, 0010101h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 0000000h, 05f5f5fh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0edededh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0bdbdbdh, 0d6d6d6h, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh
      DD 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh, 0ffffffh

